DROP INDEX IF EXISTS idx_tasks_status;
ALTER TABLE tasks DROP CONSTRAINT IF EXISTS fk_tasks_user_id;
ALTER TABLE tasks DROP COLUMN IF EXISTS completed_at;
ALTER TABLE tasks DROP COLUMN IF EXISTS updated_at;
ALTER TABLE tasks DROP COLUMN IF EXISTS user_id;
ALTER TABLE tasks DROP COLUMN IF EXISTS status;
ALTER TABLE tasks DROP COLUMN IF EXISTS author;
ALTER TABLE tasks DROP COLUMN IF EXISTS description;